---
abstract: 'multi-value capable .ini file reader (for plugins)'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Config::INI::MVP::Reader
name: Config-INI-MVP
no_index:
  directory:
    - inc
    - t
requires:
  Config::INI::Reader: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/config-ini-mvp
version: 0.019
